---
- name: Upload private docker registry certificates
  hosts: all
  become: yes

  vars:
    cert_path: tls.crt

  tasks:
  - name: Copy certificate
    ansible.builtin.copy:
      src: "{{ cert_path }}"
      dest: /usr/local/share/ca-certificates/ca.crt

  - name: Update CA store
    ansible.builtin.command:
      cmd: update-ca-certificates

  - name: Check if Docker is installed
    ansible.builtin.package:
      name: docker-ce
      state: present
    check_mode: yes
    ignore_errors: yes
    register: docker_check
   
  - name: Restart docker
    ansible.builtin.service:
      name: docker
      state: restarted
    when: docker_check is succeeded
