---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName | quote }}
      containers:
      - name: service
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        imagePullPolicy: Always
        ports:
        - name: http-port
          protocol: TCP
          containerPort: 8080
        {{- if .Values.mysql.enabled }}
        env:
        - name: MYSQL_URL
          value: "jdbc:mysql://127.0.0.1:3306/{{ .Values.mysql.database }}"
        - name: MYSQL_USER
          value: {{ .Values.mysql.username | quote }}
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.passwordSecretName }}
              key: MYSQL_PASS
        {{- end }}
        args: {{ .Values.args }}
        livenessProbe:
          httpGet:
            path: "{{ .Values.path }}/"
            port: http-port
          initialDelaySeconds: 100
        readinessProbe:
          httpGet:
            path: "{{ .Values.path }}/"
            port: http-port
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"            
      {{- if .Values.mysql.enabled }}
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.30.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-log_debug_stdout"
          - "-instances={{ .Values.mysql.connectionName }}=tcp:3306"
        securityContext:
          runAsNonRoot: true
      {{- end }}
