---
- name: Create build directory
  ansible.builtin.file: 
    path: /build 
    state: directory

- name: Copy Dockerfile
  ansible.builtin.copy:
    src: "{{ work_dir }}/{{ item }}"
    dest: "/build/{{ item }}"
    mode: "755"
  loop:
    - "{{ dockerfile }}"
    - mvnw
    - .mvn/
    - pom.xml
    - src/

- name: Login to Docker registry
  community.docker.docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"

- name: Build and push Docker image
  community.docker.docker_image:
    build:
      path: /build/
      dockerfile: "{{ dockerfile }}"
    name: "{{ registry_url }}/{{ image_name }}"
    tag: "{{ image_tag }}"
    push: yes
    source: build

- name: Logout from Docker registry
  community.docker.docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ registry_username }}"
    state: absent
