---
- name: Install required system packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: latest
    update_cache: yes

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

- name: Install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
