apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
type: Opaque
data:
  htpasswd: |-
        {{ .Files.Get .Values.htpasswdFilePath | b64enc }}
