apiVersion: v1
kind: Secret
metadata:
  name: certs-secret
type: Opaque
data:
  tls.crt: |-
        {{ .Files.Get .Values.certFilePath | b64enc }}
  tls.key: |-
        {{ .Files.Get .Values.certKeyPath | b64enc }}