apiVersion: v1
kind: Secret
metadata:
  name: certs-secret
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: |-
        {{ .Files.Get .Values.certFilePath | b64enc }}
  tls.key: |-
        {{ .Files.Get .Values.certKeyPath | b64enc }}