---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-registry-ilb
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.regional-static-ip-name: {{ .Values.staticAddressName | quote }}
    kubernetes.io/ingress.class: "gce-internal"
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: certs-secret
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: docker-registry-svc
            port:
              name: https-port
