---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-registry-ilb
  annotations:
    kubernetes.io/ingress.regional-static-ip-name: {{ .Values.staticAddressName }}
    kubernetes.io/ingress.class: "gce-internal"
    kubernetes.io/ingress.allow-http: "false"
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ .Values.preSharedCert }}
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: docker-registry-svc
            port:
              name: https-port
