apiVersion: v1
kind: Secret
metadata:
  name: sa-secret
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
type: Opaque
data:
  service-account.json: |-
        {{ .Files.Get .Values.serviceAccountKeyPath | b64enc }}
