---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-svc
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    {{- include "docker-registry.selectorLabels" . | nindent 4 }}
  ports:
  - name: https-port
    protocol: TCP
    port: 443
    targetPort: 5000
