---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-svc
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
  - name: https-port
    protocol: TCP
    port: 443
    targetPort: 5000
