steps:
- name: 'openjdk:11'
  entrypoint: './mvnw'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         '${_ARTIFACT_REGISTRY_REPO}/images/spring-petclinic:$SHORT_SHA',
         '-t',
         '${_ARTIFACT_REGISTRY_REPO}/images/spring-petclinic:latest',
         '-f',
         'spring-petclinic.dockerfile',
         '.']
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['package', 'spring-petclinic-chart/']  
  env:
  - 'SKIP_CLUSTER_CONFIG=true'
- name: 'bash'
  args: 
  - '-c'
  - |-
    awk '/version/{print $2}' spring-petclinic-chart/Chart.yaml > _VERSION
- name: 'gcr.io/$PROJECT_ID/helm'
  entrypoint: 'bash'
  args: ['-c',
         'helm push spring-petclinic-chart-$(cat _VERSION).tgz oci://${_ARTIFACT_REGISTRY_REPO}/charts']
  env:
  - 'SKIP_CLUSTER_CONFIG=true'

images: [
  '${_ARTIFACT_REGISTRY_REPO}/images/spring-petclinic:$SHORT_SHA',
  '${_ARTIFACT_REGISTRY_REPO}/images/spring-petclinic:latest',
]

options:
  logging: CLOUD_LOGGING_ONLY
