---
- name: Copy Service Account key
  ansible.builtin.copy:
    src: "{{ service_account_key_path }}"
    dest: /deploy/service-account.json

- name: Login with service account
  ansible.builtin.command:
    cmd: "gcloud auth activate-service-account --key-file=/deploy/service-account.json"

- name: Get GKE cluster credentials
  ansible.builtin.command:
    cmd: "gcloud container clusters get-credentials {{ cluster_name }} --region {{ location }} --project {{ project_id }}"
