---
- name: Copy Service Account key
  ansible.builtin.copy:
    src: "{{ service_account_key_path }}"
    dest: /sa/service-account.json

- name: Login with service account
  ansible.builtin.command:
    cmd: "gcloud auth activate-service-account --key-file=/sa/service-account.json"

- name: Get CI Kubernetes cluster credentials
  ansible.builtin.command:
    cmd: "KUBECONFIG=/.kube/config gcloud container clusters get-credentials {{ cluster_name }} --zone {{ location }} --project {{ project_id }}"
