---
- name: Install required system packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - python3-pip
    state: latest
    update_cache: yes

- name: Add gcloud CLI GPG apt Key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add gcloud CLI Repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.cloud.google.com/apt cloud-sdk main
    state: present

- name: Install gcloud CLI and kubectl
  ansible.builtin.apt:
    name: 
      - google-cloud-sdk
      - kubectl
    state: latest
    update_cache: true

- name: Add helm apt Key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add helm Repository
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Install helm
  ansible.builtin.apt:
    name: helm
    state: latest
    update_cache: true

- name: Install YAML Module for Python
  ansible.builtin.pip:
    name: PyYAML

- name: Create deploy directory
  ansible.builtin.file: 
    path: /deploy
    state: directory