---
- name: Install Google Cloud CLI
  import_tasks: install-gcloud.yml

- name: Setup variables depending on Environment
  import_tasks: vars.yml

- name: Get Kubernetes cluster credentials
  import_tasks: cluster-credentials.yml

- name: Deploy Helm release from local chart
  import_tasks: deploy-chart.yml
