---
- name: Set CI Kubernetes cluster name
  ansible.builtin.set_fact:
    cluster_name: "{{ ci_cluster_name }}"
    mysql:
      enabled: True
      database: "{{ mysql_database }}"
      username: "{{ mysql_username }}"
      password: "{{ mysql_password }}"
      connectionName: "{{ mysql_connection_name }}"
      serviceAccount: "{{ mysql_service_account }}"
    loadBalancer:
      type: "external"
      addressName: "spring-petclinic-static-ip"
      domains:
      - "spring-petclinic.tk"      
  when: env_name == "ci"

- name: Set QA Kubernetes cluster name
  ansible.builtin.set_fact:
    cluster_name: "{{ qa_cluster_name }}"
  when: env_name == "qa"
