---
- name: Set CI Kubernetes cluster name
  ansible.builtin.set_fact:
    cluster_name: "{{ ci_cluster_name }}"
    mysql:
      enabled: True
      database: "{{ mysql_database }}"
      username: "{{ mysql_username }}"
      password: "{{ mysql_password }}"
      connecttion_anme: "{{ mysql_connection_name }}"
      service_account_anme: "{{ mysql_service_account_name }}"
  when: env_name == "ci"

- name: Set QA Kubernetes cluster name
  ansible.builtin.set_fact:
    cluster_name: "{{ qa_cluster_name }}"
    mysql:
      enabled: False
  when: env_name == "qa"
