---
- name: Set CI Kubernetes cluster name
  ansible.builtin.set_fact:
    cluster_name: "{{ ci_cluster_name }}"
    replicas: 3
    mysql:
      enabled: True
      database: "{{ mysql_database }}"
      username: "{{ mysql_username }}"
      password: "{{ mysql_password }}"
      connectionName: "{{ mysql_connection_name }}"
      serviceAccount: "{{ mysql_service_account }}"
    load_balancer:
      type: "external"
      addressName: "spring-petclinic-static-ip"
      domains:
      - "spring-petclinic.tk"      
  when: env_name == "CI"

- name: Set QA Kubernetes cluster name
  ansible.builtin.set_fact:
    cluster_name: "{{ qa_cluster_name }}"
    replicas: 1
    mysql:
      enable: False
    load_balancer:
      type: "internal"
      addressName: "internal-spring-petclinic-ip"
      preSharedCert: "project-cert"
  when: env_name == "QA"
