---
- name: Set CI Kubernetes cluster name
  ansible.builtin.set_fact:
    helm_release_namespace: "petclinic-ci"
    values:
      mysql:
        database: "{{ mysql_database }}"
        username: "{{ mysql_username }}"
        password: "{{ mysql_password }}"
        cloudsqlProxy: True
        connectionName: "{{ mysql_connection_name }}"
        serviceAccount: "{{ mysql_service_account }}"
      load_balancer:
        type: "external"
        addressName: "spring-petclinic-static-ip"
        domains:
        - "{{ domain }}"
  when: env_name == "CI"

- name: Set QA Kubernetes cluster name
  ansible.builtin.set_fact:
    helm_release_namespace: "petclinic-qa"
    values:
      mysql:
        database: "{{ mysql_database }}"
        username: "{{ mysql_username }}"
        password: "{{ mysql_password }}"
  when: env_name == "QA"
