controller:
  image: "docker-registry.project.com/jenkins"
  tag: "1.0.0"
  imagePullSecretName: "registry-secret"
  installPlugins: false
  
  jenkinsUrlProtocol: "https" 	
  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    hostName: "jenkins.project.com"
    annotations:
      kubernetes.io/ingress.regional-static-ip-name: "jenkins-static-ip"
      kubernetes.io/ingress.class: "gce-internal"
      ingress.gcp.kubernetes.io/pre-shared-cert: "project-cert"
      kubernetes.io/ingress.allow-http: "false"
  secondaryingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: "jenkins-webhook-static-ip"
      kubernetes.io/ingress.class: "gce"
    paths:
    - /generic-webhook-trigger/invoke

  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        users:
        - id: ${admin-credentials-username}
          name: ${admin-credentials-username}
          password: ${admin-credentials-password}
    authorizationStrategy: |-
      globalMatrix:
        permissions:
          - "GROUP:Overall/Read:authenticated"
          - "USER:Overall/Administer:${admin-credentials-username}"

agent:
  podTemplates:
    ansible: |
      - name: ansible
        label: ansible
        containers:
        - name: ansible
          image: docker-registry.project.com/ansible:1.0.0
          ttyEnabled: true
        imagePullSecrets:
        - name: registry-secret
