controller:
  image: "docker-registry.project.com/jenkins"
  tag: "1.0.0"
  imagePullSecretName: "registry-secret"
  installPlugins: false
  nodeSelector:
    cloud.google.com/gke-nodepool: default-node-pool
  
  jenkinsUrlProtocol: "https" 	
  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    hostName: "jenkins.project.com"
    annotations:
      kubernetes.io/ingress.regional-static-ip-name: "jenkins-static-ip"
      kubernetes.io/ingress.class: "gce-internal"
      ingress.gcp.kubernetes.io/pre-shared-cert: "project-cert"
      kubernetes.io/ingress.allow-http: "false"
  secondaryingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: "jenkins-webhook-static-ip"
      kubernetes.io/ingress.class: "gce"
    paths:
    - /github-webhook

  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        users:
        - id: ${user-credentials-admin-username}
          name: ${user-credentials-admin-username}
          password: ${user-credentials-admin-password}
        - id: ${user-credentials-webhook-username}
          name: ${user-credentials-webhook-username}
          password: ${user-credentials-webhook-password}
    authorizationStrategy: |-
      globalMatrix:
        permissions:
          - "GROUP:Overall/Read:authenticated"
          - "USER:Overall/Administer:${user-credentials-admin-username}"

agent:
  nodeSelector:
    cloud.google.com/gke-nodepool: default-node-pool

additionalAgents:
  ansible:
    podName: ansible
    customJenkinsLabels: ansible
    sideContainerName: jnlp
    image: docker-registry.project.com/ansible
    tag: 1.0.0
    imagePullSecretName: registry-secret
