plugin: gcp_compute
projects:
  - PROJECT_ID
filters:
  - labels.ansible:*
service_account_file: ANSIBLE_SA_KEY_PATH
auth_kind: serviceaccount
scopes:
  - 'https://www.googleapis.com/auth/compute.readonly'
keyed_groups:
  - key: labels.ansible
leading_separator: no
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].networkIP
