image: ""
imagePullSecrets: 
  - name: registry-secret

mysql:
  enabled: false
# database: petclinic
# user: petclinic
# password: petclinic
# connectionName: cloudsql-connection-name
# serviceAccountName: kubernetes-service-account
