image: docker-registry.project.com/spring-petclinic:latest
imagePullSecrets: 
  - name: registry-secret
autoscaling:
  enabled: false
# minReplicas: 1
# maxReplicas: 5
# targetCPUUtilizationPercentage: 60
# targetMemoryUtilizationPercentage: 60
replicas: 1
nodeSelector:
  cloud.google.com/gke-nodepool: app-node-pool

mysql:
  database: petclinic
  username: petclinic
  password: petclinic
  cloudsqlProxy: false
# Next values should be provided if cloudsqlProxy is true:
# connectionName: cloudsql-connection-name
# serviceAccount: gcp-service-account

loadBalancer:
  type: internal
  addressName: internal-spring-petclinic-ip
# Self-managed SSL certificate should be provided for internal Load Balancer 
  preSharedCert: project-cert
# Public domains should be provided for external Load Balancer 
# domains:
# - spring-petclinic.com
