image: ""
tag: "latest"
serviceAccountName: ""
port: 80
args: []
autoscaling:
  enabled: false
# minReplicas: 1
# maxReplicas: 5
# targetCPUUtilizationPercentage: 60
# targetMemoryUtilizationPercentage: 60
replicas: 1
nodeSelector:
  cloud.google.com/gke-nodepool: app-node-pool

mysql:
  enabled: false
  database: example
  username: user
  passwordSecretName: mysql-secret
  connectionName: cloudsql-connection-name
