---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spring-petclinic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-petclinic.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.mysql.cloudsqlProxy }}
      serviceAccountName: sql-proxy-sa
      {{- end }}
      containers:
      - name: spring-petclinic
        image: {{ .Values.image | quote }}
        imagePullPolicy: Always
        ports:
        - name: http-port
          protocol: TCP
          containerPort: 8080
        env:
        - name: MYSQL_URL
          value: "jdbc:mysql://127.0.0.1:3306/{{ .Values.mysql.database }}"
        - name: MYSQL_USER
          value: {{ .Values.mysql.username }}
        - name: MYSQL_PASS
          value: {{ .Values.mysql.password }}
        args: ["--spring.profiles.active=mysql"]
        livenessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 100
        readinessProbe:
          httpGet:
            path: /
            port: http-port
      {{- if .Values.mysql.cloudsqlProxy }}
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.30.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-log_debug_stdout"
          - "-instances={{ .Values.mysql.connectionName }}=tcp:3306"
        securityContext:
          runAsNonRoot: true
      {{- else }}
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.password }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.username }}
        - name: MYSQL_PASSWORD
          values: {{ .Values.mysql.password }}
        - name: MYSQL_DATABASE
          values: {{ .Values.mysql.database }}
        ports:
        - name: mysql-port
          protocol: TCP
          containerPort: 3306
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-volume
        emptyDir: {}
      {{- end }}

