---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: spring-petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.mysql.enabled }}
      serviceAccountName: sql-proxy-sa
      {{- end }}
      containers:
      - name: spring-petclinic
        image: {{ .Values.image | quote }}
        imagePullPolicy: Always
        ports:
        - name: http-port
          protocol: TCP
          containerPort: 8080
        {{- if .Values.mysql.enabled }}
        env:
        - name: MYSQL_URL
          value: "jdbc:mysql://127.0.0.1:3306/{{ .Values.mysql.database }}"
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_PASS
          value: {{ .Values.mysql.password }}
        args: ["--spring.profiles.active=mysql"]
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
      {{- if .Values.mysql.enabled }}
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.30.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-log_debug_stdout"
          - "-instances={{ .Values.mysql.connectionName }}=tcp:3306"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
      {{- end }}

