---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.loadBalancer.type "external" }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.loadBalancer.addressName }}
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
    {{- else if eq .Values.loadBalancer.type "internal" }}
    kubernetes.io/ingress.regional-static-ip-name: {{ .Values.loadBalancer.addressName }}
    kubernetes.io/ingress.class: "gce-internal"
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ .Values.loadBalancer.preSharedCert }}
    kubernetes.io/ingress.allow-http: "false"
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080



