{{- if .Values.mysql.cloudsqlProxy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sql-proxy-sa
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.mysql.serviceAccount }}
{{- end }}
