{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sql-proxy-sa
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.mysql.serviceAccount }}
{{- end }}
