---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: spring-petclinic
spec:
  type: NodePort
  selector:
    app: spring-petclinic
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
