---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "spring-petclinic.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
